[unstable]
build-std = ["core", "alloc", "compiler_builtins"]

[target.wasm32-unknown-unknown]
rustflags = [
  "-C",
  "target-cpu=mvp",
  "-C",
  "target-feature=-bulk-memory",
  "-C",
  "link-arg=--allow-undefined",
]
